name: astrologyapp
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.6
  auto_size_text: ^3.0.0-nullsafety.0
  provider: ^5.0.0
  razorpay_flutter: ^1.2.7
  
  firebase_core: ^1.4.0
  firebase_storage: ^10.0.1
  cloud_firestore: ^2.4.0
  firebase_auth: ^2.0.0

  googleapis: ^4.0.0
  googleapis_auth: ^1.1.0
  google_sign_in: ^5.0.4

  intl: ^0.17.0
  url_launcher: ^6.0.9
  rive: ^0.7.2
  line_icons: ^2.0.0
  multiselect_formfield: ^0.1.6
  #chips_choice: ^2.0.1
  image_picker: ^0.8.3+2
  fluttertoast: ^8.0.8
  photo_view: ^0.12.0
  flutter_local_notifications: ^8.1.1+1
  firebase_messaging: ^10.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
  - assets/images/1.png
  - assets/images/3.jpg
  - assets/images/bro.jpg
  - assets/images/noimage.png
  - assets/images/space.png
  - assets/images/mimi1.gif
  - assets/images/mimi2.gif
  - assets/images/mimi3.gif
  - assets/images/mimi4.gif
  - assets/images/mimi5.gif
  - assets/images/mimi6.gif
  - assets/images/mimi7.gif
  - assets/images/mimi8.gif
  - assets/images/mimi9.gif
  - assets/Rive/Aquarius.riv
  - assets/Rive/Aries.riv
  - assets/Rive/astro.riv
  - assets/Rive/cancer.riv
  - assets/Rive/Capricorn.riv
  - assets/Rive/gemini.riv
  - assets/Rive/libra.riv
  - assets/Rive/lio.riv
  - assets/Rive/pisccs.riv
  - assets/Rive/Sagittarius.riv
  - assets/Rive/Scorpio.riv
  - assets/Rive/taurus.riv
  - assets/Rive/virgo.riv
  - assets/Rive/astrology/Aquarius.riv
  - assets/Rive/astrology/Aries.riv
  - assets/Rive/astrology/astro.riv
  - assets/Rive/astrology/cancer.riv
  - assets/Rive/astrology/Capricorn.riv
  - assets/Rive/astrology/gemini.riv
  - assets/Rive/astrology/libra.riv
  - assets/Rive/astrology/lio.riv
  - assets/Rive/astrology/pisccs.riv
  - assets/Rive/astrology/Sagittarius.riv
  - assets/Rive/astrology/Scorpio.riv
  - assets/Rive/astrology/taurus.riv
  - assets/Rive/astrology/virgo.riv
  #   - images/a_dot_ham.jpeg
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
