name: astrologyapp
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.6
  auto_size_text: ^3.0.0-nullsafety.0
  provider: ^5.0.0
  razorpay_flutter: ^1.2.7
  
  firebase_core: ^1.4.0
  firebase_storage: ^10.0.1
  cloud_firestore: ^2.4.0
  firebase_auth: ^2.0.0

  googleapis: ^4.0.0
  googleapis_auth: ^1.1.0
  google_sign_in: ^5.0.4

  intl: ^0.17.0
  url_launcher: ^6.0.9
  rive: ^0.7.2
  line_icons: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
  - assets/1.png
  - assets/3.jpg
  - assets/bro.jpg
  - assets/astro.riv
  #   - images/a_dot_ham.jpeg
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
